@startuml
'https://plantuml.com/sequence-diagram
skinparam style strictuml
'autonumber
hide footbox

'title Méthode jouer()
participant ":Main" as main
participant "controlFourmi:ControlFourmi" as controlFourmi
participant "fourmi:Fourmi" as fourmi
participant "position:Noeud" as position
participant "voisin:Noeud" as voisin
participant "freeVoisin:Noeud[*]" as freeVoisins
entity "rand:Random" as random

'Pour le bitset.. prof a dit pas besoin
'participant ":Graphe" as graphe
'participant "bitPlay:BitSet[][]" as bitPlay
'participant "bitPlay[i][j]:BitSet" as bitSet

main -> controlFourmi ++ : play(1, false)
    loop fourmi : "controlFourmi.Fourmis
    |||
        controlFourmi -> fourmi ++ : move()
        fourmi -> fourmi  ++ : getPosition()
        return position

        fourmi -> position ++ : getFreeVoisins()
            position -> position ++ : getVoisins()
            return voisins
            loop voisin : voisins
                alt voisin.isFree() == true
                    position -> freeVoisins : add(voisin)
                end
            end
        return freeVoisins

        'nextInt() en Java
        fourmi -> random ++ : getInt(freeVoisins.size)
        return randomInt

        alt freeVoisins.size() != 0
            fourmi -> fourmi : setPosition(freeVoisin[randomInt])
        end
        deactivate fourmi
    end
|||
    'controlFourmi -> graphe ++ : getHeight
    'return height
    'controlFourmi -> graphe ++ : getWidth
    'return width

    'create bitPlay
    'controlFourmi -->> bitPlay : instanciate(height, width)
        'loop height
            'loop width
                'create bitSet
                'controlFourmi -->> bitSet : instanciate(7)

                'controlFourmi -> graphe ++ : getNoeud(height,width)
                'return noeud
                'alt noeud.getNoeudState == STATE.ANTHILL
                    'controlFourmi -> bitSet : set(0,true)
                'end
                'alt noeud.getNoeudState == STATE.ANTHILL
                    'controlFourmi -> bitSet : set(0,true)
                'end
            'end
            'return bitPlay
        'end

deactivate controlFourmi



@enduml