@startuml
'https://plantuml.com/sequence-diagram
skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam circledCharacterRadius 0
skinparam circledCharacterFontSize 0
skinparam classFontStyle Bold
'autonumber

interface AntFacadeController<<interface>>{

}

enum STATE <<enum>> {
    FREE
    OBSTACLE
    ANTHILL
}


class Graphe {
     -width:Integer
     -height:Integer
     -noeudList:List<Noeud>
}
class Noeuds{
    -voisin:ArrayList<Noeud>
    -noeudState:STATE
}

abstract Fourmi <<abstract>>{

}

class Reine extends Fourmi{

}

class Soldat extends Fourmi{

}

class ControlFourmi implements AntFacadeController{

}

Noeuds -> Noeuds : est voisin de >
ControlFourmi --> Graphe : possède un >
ControlFourmi ---> Fourmi : possède des >
Graphe --> Noeuds : composé de >
Fourmi  -> Noeuds : est sur le >
Noeuds -->  STATE : est >

@enduml