@startuml
'https://plantuml.com/sequence-diagram
skinparam style strictuml
'autonumber
hide footbox

'title Méthode jouer()
participant ":Main" as main
participant "controlAnt:ControlAnt" as controlAnt
participant "fourmi:Fourmi" as ant
participant "position:Noeud" as position
participant "voisin:Noeud" as voisin
participant "freeVoisins:Noeud[*]" as freeVoisins
entity "rand:Random" as random

'Pour le bitset.. prof a dit pas besoin
'participant ":Graphe" as graphe
'participant "bitPlay:BitSet[][]" as bitPlay
'participant "bitPlay[i][j]:BitSet" as bitSet

main -> controlAnt ++ : play(1, false)
    loop ant : controlAnt.Ant
    |||
        controlAnt -> ant ++ : move()
        ant -> ant  ++ : getPosition()
        return position

        ant -> position ++ : getFreeVoisins()
            position -> position ++ : getVoisins()
            return voisins
            loop voisin : voisins
                alt voisin.getNoeudState() != STATE.OBSTACLE
                    position -> freeVoisins : add(voisin)
                end
            end
        return freeVoisins



        alt freeVoisins.size() != 0
            'nextInt() en Java
            ant -> random ++ : getInt(freeVoisins.size)
            return randomInt

            ant -> ant : setPosition(freeVoisin[randomInt])
        end
        deactivate ant
    end
|||
    'controlFourmi -> graphe ++ : getHeight
    'return height
    'controlFourmi -> graphe ++ : getWidth
    'return width

    'create bitPlay
    'controlFourmi -->> bitPlay : instanciate(height, width)
        'loop height
            'loop width
                'create bitSet
                'controlFourmi -->> bitSet : instanciate(7)

                'controlFourmi -> graphe ++ : getNoeud(height,width)
                'return noeud
                'alt noeud.getNoeudState == STATE.ANTHILL
                    'controlFourmi -> bitSet : set(0,true)
                'end
                'alt noeud.getNoeudState == STATE.ANTHILL
                    'controlFourmi -> bitSet : set(0,true)
                'end
            'end
            'return bitPlay
        'end

deactivate controlAnt



@enduml