@startuml
'https://plantuml.com/sequence-diagram
skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam circledCharacterRadius 0
skinparam circledCharacterFontSize 0
skinparam classFontStyle Bold
'autonumber


interface AntFacadeController<<interface>>{

}

enum STATE <<enum>> {
    FREE
    OBSTACLE
    ANTHILL
}


class Graph {
     width
     height
}
class Node{
}

abstract Ant <<abstract>>{

}

class Queen extends Ant{

}

class Soldier extends Ant{

}

class Worker extends Ant{
}

class ControlAnt implements AntFacadeController{

}

Node - Node : est voisin de >
ControlAnt -- Graph : possède un >
ControlAnt --- Ant : possède des >
Graph -- Node : composé de >
Ant  - Node : est sur le >
Node --  STATE : est >

@enduml