@startuml
'https://plantuml.com/sequence-diagram
skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam circledCharacterRadius 0
skinparam circledCharacterFontSize 0
skinparam classFontStyle Bold
'autonumber

class Graphe {
    +createGrid(int width, int height)
    +putObstacle(int row, int column)
}
class Noeud{
    -Obstacle:boolean
    +isFree():boolean
    +getVoisins():Noeud[*]
}

abstract Fourmi {
    +getNoeud()
}
class Reine extends Fourmi{
    +createColony(int row, int column)
    +createSoldiers(int amount)
}
class Soldat extends Fourmi{
    +deplacer()
}

Graphe "-noeuds\n0..n" *--> Noeud : composé de >
Fourmi "-position\n1" -> Graphe : est sur le >
Noeud "-voisins\n0..*" -> Noeud : est voisin de >

@enduml