@startuml
'https://plantuml.com/sequence-diagram
allow_mixing
skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam circledCharacterRadius 0
skinparam circledCharacterFontSize 0
skinparam classFontStyle Bold
'autonumber

'Controleur
interface AntFacadeController <<interface>> {
    '+setParameters( evaporationParam:Integer, foodParam:Integer, pheromoneParam:Integer )
    +createColony(row:Integer,column:Integer)
    +createGrid(width:Integer, height:Integer)
    +putObstacle(row:Integer, column:Integer)
    '+putFood( row:Integer, column:Integer, quantity:Integer);
    '+createWorkers( amount:Integer )
    +createSoldiers(amount:Integer)
    '+setAntFile(antLogFile:String);
    +play( duration:Integer, record:boolean )
}

class Noeud {
    -free:boolean
    +isFree():boolean
    +setFree(boolean)
    +getVoisins():Noeud[*]
}

abstract Fourmi <<abstract>> {
    +getPosition():Noeud
    +deplacer()
}
class Reine{
    +deplacer()

}
class Soldat{
    +deplacer()
}


'class Graphe implements AntFacadeController{
class ControlFourmi implements AntFacadeController{

}

class ControlFourmi{
}

class Graphe{
 +getNoeud(row:Integer, column:Integer):Noeud
}


Soldat --|> Fourmi
Reine -l-|> Fourmi

ControlFourmi "1 " *-l-> Graphe
ControlFourmi "1..*" *--> Fourmi

Graphe *-r-> "-noeuds\n0..n" Noeud : composé de >
Fourmi "-fourmi\n0..n" -- "-position\n1" Noeud  : est sur un >
Noeud "-voisins\n0..*" -> Noeud : est voisin de >

@enduml