@startuml
'https://plantuml.com/sequence-diagram
skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam circledCharacterRadius 0
skinparam circledCharacterFontSize 0
skinparam classFontStyle Bold
'autonumber

class Graphe {
    +createColony(int row, int column)
    +createGrid(int width, int height)
    +putObstacle(int row, int column)
}
class Noeud{
    -free:boolean
    +isFree():boolean
    +setFree(boolean)
    +getVoisins():Noeud[*]
}

abstract Fourmi {
    +getPosition():Noeud
}
class Reine extends Fourmi{

    +createSoldiers(int amount)
}
class Soldat extends Fourmi{
    +deplacer()
}

Graphe "-noeuds\n0..n" *-u-> Noeud : composé de >
Fourmi "-position\n1" -> Noeud : est sur le >
Noeud "-voisins\n0..*" -> Noeud : est voisin de >

@enduml