@startuml
'https://plantuml.com/sequence-diagram
skinparam style strictuml
'autonumber
hide footbox

'title Méthode jouer()
participant ":Main" as main
participant "controlFourmi:ControlFourmi" as controlFourmi
participant ":Graphe" as graphe
participant ":Noeud" as noeud
participant "noeud2:Noeud" as noeud2
participant "fourmi:controlFourmi.Fourmis" as fourmi

main -> controlFourmi ++ : play(1, false)
    loop fourmi : "controlFourmi.Fourmis
    |||
        controlFourmi -> fourmi : deplacer()
    end

deactivate controlFourmi




@enduml